version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql1
    ports:
      - 3405:3405
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: devdojo
    volumes:
      - microservices_devdojo:/var/lib/mysql

volumes:
  microservices_devdojo: